title: "奇幻菌的奇想手记"
description: "记一点日常，写一点奇想。喵❤️～"
author: Aneko
lang: zh-CN
timezone: Asia/Shanghai
url: "https://aneko-qhj.github.io"
baseurl: ""
source_url: "https://github.com/Aneko-QhJ/Aneko-QhJ.github.io"
theme: null
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - scripts
  - docs
  - README.md
  - Gemfile
  - Gemfile.lock
