title: "Aneko 的奇想手记"
description: "记一点日常，写一点奇想。喵～"
author: Aneko
lang: zh-CN
timezone: Asia/Shanghai
url: "https://livcm.github.io"
baseurl: ""
source_url: "https://github.com/livcm/livcm.github.io"
theme: null
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - docs
  - README.md
  - Gemfile
  - Gemfile.lock
